### ISSUE TITLE
Enhancement: Filter(s) for removing temperature reports from serial.log(s)

### ISSUE THREAD

**Issue by b-morgan** [OctoPrint/bundleviewer.octoprint.org#3]
Duplicating the terminal tab filters in the bundle viewer when viewing a serial.log would be extremely useful.

**Comment by foosel** [comment]
@b-morgan Sorry for the very late response to this, but *gestures widely*

I'm a bit unsure about what this would accomplish in the context of the bundleviewer. Given that it is a debugging tool, even temperature lines are usually important, as their timing information can give infos on how the printed processes commands and how long it needs to process queries and such.

In the context of OctoPrint's terminal tab, yes, they can be unwelcome noise, but in the context of viewing serial.log from a system info bundle, I find them quite important for the full picture, just like every other single line.

Can you elaborate?

**Comment by b-morgan** [comment]
The terminal tab filters are check boxes so they can be turned on or off as necessary. I agree that the timing information is important but scrolling through uninteresting temperature reports until you find the point in the log where something interesting happened can be tedious. Once you find that point, uncheck the filter to see the whole picture.

Perhaps we should think about this enhancement more along the lines of "skip to the next non-temperature entry" or "non-SD message entry".

My use of the bundle viewer is much different that your use of it. I suggested this enhancement because it would make my usage better.

**Comment by foosel** [comment]
Roger, makes sense.

**Comment by foosel** [comment]
Implemented as of #7 and some more tinkering on my side.
