### ISSUE TITLE
[Bug] Octoprint Bundle Viewer marks only parts of the line

### ISSUE THREAD

**Issue by PowerWiesel** [OctoPrint/bundleviewer.octoprint.org#5]
Only the part of the lines visible at the beginning will be marked after the search - after scrolling to the right, the marking will be cut off.

See pictures
![Bildschirmfoto vom 2022-06-26 02-02-20](https://user-images.githubusercontent.com/11167590/175794331-55eb1c44-a0c1-4ea6-9102-1f55868126f9.png)
![Bildschirmfoto vom 2022-06-26 02-02-30](https://user-images.githubusercontent.com/11167590/175794334-0eced632-ffc5-4672-acd9-93ff3c7d34e6.png)

**Comment by foosel** [comment]
Should be fixed thanks to #8
